// Generated by CoffeeScript 1.8.0
var app, bodyParser, express, request;

express = require('express');

bodyParser = require('body-parser');

request = require('request');

app = express();

app.use(bodyParser({
  limit: '50mb'
}));

app.listen(3000);

app.get('/client/connected', function(req, res) {
  return request("http://localhost/dbms/core/clientConnected.php?id=" + req.query.id, function(err, httpRes, body) {
    return res.end();
  });
});

app.get('/client/disconnected', function(req, res) {
  return request("http://localhost/dbms/core/clientDisconnected.php?id=" + req.query.id, function(err, httpRes, body) {
    return res.send(body);
  });
});

app.get('/schema', function(req, res) {
  res.header('Access-Control-Allow-Origin', '*');
  return request("http://localhost/dbms/core/main.php?schema=1&db=" + req.query.db, function(err, httpRes, body) {
    return res.send(body);
  });
});

app.get('*', function(req, res) {
  return request("http://localhost/dbms/core/main.php?resource=" + req.path + "&db=" + req.query.db + "&clientId=" + req.query.clientId, function(err, httpRes, body) {
    return res.send(body);
  });
});

app.post('/', function(req, res) {
  return request.post("http://localhost/core/dbms/main.php?db=" + req.query.db + "&clientId=" + req.query.clientId, {
    form: {
      update: req.body.update
    }
  }, function(err, httpResponse, body) {
    return res.send(body);
  });
});

//# sourceMappingURL=server.js.map
